const calculatorActionTypes = {
	SET_PRODUCT: "SET_PRODUCT",
	SET_PRODUCT_GENDER: "SET_PRODUCT_GENDER",
	SET_PRODUCT_AGE_AMOUNT: "SET_PRODUCT_AGE_AMOUNT",
	SET_PRODUCT_AGE_TIMESCALE: "SET_PRODUCT_AGE_TIMESCALE",
	SET_MATERIAL_DISTRIBUTION: "SET_MATERIAL_DISTRIBUTION",
	SET_MANUFACTURING_COUNTRY: "SET_MANUFACTURING_COUNTRY",
	SET_COUNTRY_OF_RESIDENCELD: "SET_COUNTRY_OF_RESIDENCELD",
	SET_WASHING: "SET_WASHING",
	SET_MONTLY_LAUNDRY_FREQUENCY: "SET_MONTLYLAUNDRYFREQUENCY",
	SET_MACHINE_SETTING: "SET_MACHINE_SETTING",
	SET_DRYING_METHOD: "SET_DRYING_METHOD",
	SET_WASHING_TEMPERATURE: "SET_WASHING_TEMPERATURE",
}

export const requestTypes = {
	FETCH_CALCULATOR: "FETCH_CALCULATOR",
}

export default calculatorActionTypes
